moved db to be one object defined in main
AAU-SW7-PSAAAB/energy-label-log-server pull request #17
Opened 2024-11-25 09:51 UTC by KamyaPA

Should fix the connection problems to mariadb

2024-11-25 10:51 UTC, BaBrixx commented on app/db.ts
> +		);
Default bør nok ikke være så højt

2024-11-26 09:46 UTC, DenFlyvendeGed commented on app/db.ts
> +			cli.fallback("100").get("--mariadb-conn-limit"),
50 eller 100? :)

2024-11-26 09:50 UTC, DenFlyvendeGed submitted a review, later dismissed
Yes

2024-11-26 09:53 UTC, BaBrixx requested changes

2024-11-26 09:53 UTC, BaBrixx commented on app/index.ts
>  			reply.status(200).send();
Den burde returnere 500 hvis indsættelsen fejler

2024-11-26 10:24 UTC, BaBrixx approved these changes
LGTM

2024-11-26 10:26 UTC, merged